"""
Prototype: fixing the FIRM Neumann-wall non-convergence.

Clean testbed = complex manufactured Poisson on a jittered UNIT BOX with ALL-Neumann
faces (+ one pinned dof). Baseline (FIRM projection) does NOT converge. We test
candidate boundary closures and measure the solution convergence order.

Candidate M (mirror ghosts, even reflection):
  For a boundary particle near a flat face (plane through `foot`, outward normal n),
  reflect each interior neighbour j across the plane: x_g = x_j - 2*sig*n,
  sig = (x_j - foot).n < 0. Assign the ghost the Neumann-consistent value
  p_g = p_j - 2*sig*g, g = dp/dn at the wall. The ghost is INCLUDED in M_i and o_i
  (restores symmetric support) and contributes to the Laplacian row coupling to p_j.
"""
import numpy as np

import firm_core as fc
import geometry2d as g2
import manufactured as mf
import scipy.sparse as sps
from scipy.sparse.linalg import spsolve

FIELD = mf.complex_field(np.pi, 0.3)


def gfd_row(xij, w, bclist=(), ridge=1e-10):
    """2nd-order GFD/MLS Laplacian stencil. Returns (d_j, bc_value).

    Fit f_ij ~ [dx,dy,0.5dx^2,dx*dy,0.5dy^2].coef by weighted least squares;
    Laplacian = coef_xx + coef_yy. Each Neumann constraint (normal, g) adds a
    penalty row n.grad p = g so the fit honours the flux (consistent boundary
    stencil). lap_i = sum_j d_j (f_j - f_i) + bc_value.
    """
    dx, dy = xij[:, 0], xij[:, 1]
    A = np.stack([dx, dy, 0.5 * dx * dx, dx * dy, 0.5 * dy * dy], axis=1)  # (n,5)
    c = np.array([0.0, 0.0, 1.0, 0.0, 1.0])                               # picks p_xx + p_yy
    G = A.T @ (w[:, None] * A) + ridge * np.eye(5)
    rhs_bc = np.zeros(5)
    w_bc = 1e3 * float(w.mean())
    for normal, g in bclist:
        a_bc = np.array([normal[0], normal[1], 0.0, 0.0, 0.0])
        G = G + w_bc * np.outer(a_bc, a_bc)
        rhs_bc += w_bc * a_bc * g
    Ginv = np.linalg.inv(G)
    d = c @ Ginv @ (A.T * w)
    bc_value = float(c @ Ginv @ rhs_bc)
    return d, bc_value
DXS = [0.045, 0.033, 0.025, 0.018]
FACES = [(np.array([-1.0, 0.0]), 0.0, 0), (np.array([1.0, 0.0]), 1.0, 0),
         (np.array([0.0, -1.0]), 0.0, 1), (np.array([0.0, 1.0]), 1.0, 1)]


def _faces_near(xi, h):
    """Flat box faces within h: list of (normal, foot)."""
    out = []
    for n, coord, axis in FACES:
        dist = abs(xi[axis] - coord)
        if dist < h:
            foot = xi.copy(); foot[axis] = coord
            out.append((n, foot))
    return out


def solve_box(dx, mode, field=FIELD, bc="neu", seed=7, correct=True):
    """bc='neu' -> all faces Neumann (+1 pin);  bc='dir' -> all faces Dirichlet."""
    h = 2.5 * dx
    pos = g2.jittered_box(dx, 0.3, seed)
    N = len(pos)
    nbnd = g2.box_interior_mask(pos, h)
    nl = fc.neighbor_lists(pos, h)
    pin = int(np.argmin(np.linalg.norm(pos - 0.5, axis=1)))
    R, C, D = [], [], []
    b = np.zeros(N)

    for i in range(N):
        boundary = not nbnd[i]
        if (bc == "dir" and boundary) or (bc == "neu" and i == pin):
            R.append(i); C.append(i); D.append(1.0); b[i] = field.value(pos[i]); continue
        nb = nl[i]
        xij = pos[nb] - pos[i]
        w = fc.kernel(np.linalg.norm(xij, axis=1), h)
        faces = _faces_near(pos[i], h) if (boundary and bc == "neu") else []

        if mode == "gfd":
            bclist = [(n, float(field.grad(foot) @ n)) for n, foot in faces]
            d, bc_val = gfd_row(xij, w, bclist)
            for k, j in enumerate(nb):
                R += [i, i]; C += [j, i]; D += [d[k], -d[k]]
            b[i] = field.laplacian(pos[i]) - bc_val   # GFD lap is unnormalized (= ddx+ddy)
            continue

        if mode == "mirror" and faces:
            # mirror real neighbours across the reflection GROUP generated by the
            # near faces: single reflections + (for corners) the composed double
            # reflection R_B(R_A(.)) that fills the far quadrant (per the corner
            # double-reflection x_g,xy). Each ghost value = p_j + accumulated flux
            # increment.  comps: which faces to compose.
            fdat = [(n, foot, float(field.grad(foot) @ n)) for n, foot in faces]
            if len(fdat) == 1:
                comps = [(0,)]
            else:  # 2 near faces: A, B, and the corner composition A-then-B
                comps = [(0,), (1,), (0, 1)]
            gx, gw, gsrc, ginc = [], [], [], []
            for j in list(nb) + [i]:                       # include i itself: x_i' fills the
                for comp in comps:                         # closest, highest-weight ghost hole
                    x = pos[j].copy(); inc = 0.0
                    for fi in comp:
                        n, foot, gflux = fdat[fi]
                        sig = float((x - foot) @ n)
                        inc += -2.0 * sig * gflux
                        x = x - 2.0 * sig * n              # reflect position
                    rg = x - pos[i]
                    rr = np.linalg.norm(rg)
                    if 1e-12 < rr < h:
                        gx.append(rg); gw.append(fc.kernel(rr, h))
                        gsrc.append(j); ginc.append(inc)   # gsrc==i -> diagonal c,-c cancels; RHS keeps flux
            if gx:
                gx = np.array(gx); gw = np.array(gw)
                xij_all = np.vstack([xij, gx])
                w_all = np.concatenate([w, gw])
                gm = fc.geom_quantities(xij_all, w_all)
                # on (near-)symmetric mirror support the renormalization correction
                # is ~identity; optionally drop it (correct=False) for stability
                V = gm.B @ gm.o if correct else np.zeros(xij_all.shape[1])
                wij = fc.correction_weights(xij_all, V)
                # real neighbours
                for k, j in enumerate(nb):
                    c = w[k] * wij[k]
                    R += [i, i]; C += [j, i]; D += [c, -c]
                # ghost neighbours: couple to source, push increment to RHS
                for m, j in enumerate(gsrc):
                    c = gw[m] * wij[len(nb) + m]
                    R += [i, i]; C += [j, i]; D += [c, -c]
                    b[i] -= c * ginc[m]   # constant ghost increment moves to RHS with a MINUS
                b[i] += field.laplacian(pos[i]) / gm.N
                continue

        # baseline FIRM projection (interior, or wall without mirror)
        gm = fc.geom_quantities(xij, w)
        bwall = 0.0
        if faces:
            normals = np.array([n for n, _ in faces])
            P, Nm, Gi = fc.proj_GGP(normals, eps=0.01 if len(normals) > 1 else 0.0)
            gv = np.array([float(field.grad(foot) @ n) for n, foot in faces])
            bwall = fc.wall_flux_rhs_GGP(Nm, Gi, gm.o, gv)
            V = gm.B @ (P @ gm.o)
        else:
            V = gm.B @ gm.o
        wij = fc.correction_weights(xij, V)
        for k, j in enumerate(nb):
            c = w[k] * wij[k]
            R += [i, i]; C += [j, i]; D += [c, -c]
        b[i] += field.laplacian(pos[i]) / gm.N + bwall

    A = sps.csr_matrix((D, (R, C)), shape=(N, N))
    p = spsolve(A, b)
    pe = field.value(pos)
    err = (p - pe)[nbnd]
    ref = pe[nbnd].copy()
    if bc == "neu":                       # pure-Neumann solution is defined up to a constant
        err = err - err.mean()
        ref = ref - ref.mean()
    return np.linalg.norm(err) / max(np.linalg.norm(ref), 1e-30)


def order(errs):
    return float(np.polyfit(np.log(DXS), np.log(errs), 1)[0])


if __name__ == "__main__":
    SEEDS = [7, 11, 19, 23, 31, 42, 5, 99]

    def med(mode, bc):
        e = [float(np.median([solve_box(dx, mode, FIELD, bc, s) for s in SEEDS])) for dx in DXS]
        return e, order(e)

    print(f"Complex Poisson on a jittered box (median over {len(SEEDS)} seeds), rel-L2 interior vs dx = {DXS}")
    print("Neumann errors are mean-removed (pure-Neumann null space).\n")
    e, o = med("baseline", "dir")
    print(f"  Dirichlet (baseline) : " + " ".join(f"{v:.2e}" for v in e) + f"   order {o:5.2f}   reference ceiling")
    e, o = med("baseline", "neu")
    print(f"  Neumann  baseline    : " + " ".join(f"{v:.2e}" for v in e) + f"   order {o:5.2f}   flux-only projection")
    e, o = med("mirror", "neu")
    print(f"  Neumann  mirror-ghost: " + " ".join(f"{v:.2e}" for v in e) + f"   order {o:5.2f}   +corner +self reflections")
    e, o = med("gfd", "neu")
    print(f"  Neumann  GFD-penalty : " + " ".join(f"{v:.2e}" for v in e) + f"   order {o:5.2f}   2nd-order op, penalty flux")
    print("\n  -> ghost completion (mirror) cuts the Neumann error ~10x and removes the jitter,")
    print("     reaching the linear-consistent operator's ceiling (~order 1). True 2nd-order")
    print("     Neumann needs a 2nd-order operator with an EXACT flux constraint (GMLS/KKT).")
